name: CI/CD
on: push
permissions:
  contents: write
jobs:
  test_job:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true
          cache-key: "flutter-:os:-:channel:-:version:-:arch:-:hash:"
          cache-path: "${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:"
      - run: flutter pub get
      - run: flutter test

  web_job:
    name: Web
    runs-on: ubuntu-latest
    needs: [test_job]
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true
          cache-key: "flutter-:os:-:channel:-:version:-:arch:-:hash:"
          cache-path: "${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:"
      - run: flutter pub get
      - run: flutter build web --release --base-href /${{ github.event.repository.name }}/
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build/web
