name: CI/CD
on: push
permissions:
  contents: write
jobs:
  test_job:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true
          cache-key: "flutter-:os:-:channel:-:version:-:arch:-:hash:"
          cache-path: "${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:"
      - run: flutter pub get
      - run: flutter test

  web_job:
    name: Web deploy
    runs-on: ubuntu-latest
    needs: [test_job]
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true
          cache-key: "flutter-:os:-:channel:-:version:-:arch:-:hash:"
          cache-path: "${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:"
      - run: flutter pub get
      - run: flutter build web --release --base-href /${{ github.event.repository.name }}/
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build/web

  linux_job:
    name: Linux release
    runs-on: ubuntu-latest
    needs: [test_job]
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: |
          sudo apt-get update -y
          sudo apt-get install -y cmake clang ninja-build libgtk-3-dev
      - run: flutter build linux --release
      - run: cd build/linux/x64/release/bundle/
      - run: tar -czf ../connectionstrings-linux64.tar.gz .
      - run: cd ../../../../..
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: connectionstrings-linux64
          path: build/linux/x64/release/connectionstrings-linux64.tar.gz
